config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, controllers: { registrations: "registrations" }
  get '/profile', to: 'profile#show', as: :profile_path
  get '/profile/lookup', to: 'profile#lookup', as: :profile_lookup_path

  get '/wiki/:space_slug', to: 'spaces#show'
  get '/wiki/:space_slug/*page_slug', to: 'wiki#show'

  resources :spaces, only: [:new, :create] do
    resources :wiki, only: [:new, :create] do
      post '/spaces/:space_id/wiki', to: 'wiki#create', as: :space_wiki
    end
  end

  post '/spaces/:space_id/wiki', to: 'wiki#create', as: :space_wiki

  root to: redirect('/profile')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :organization
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :spaces, as: :owner
  accepts_nested_attributes_for :spaces
  has_many :pages, through: :spaces
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :space
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :owner, polymorphic: true
  has_many :pages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :spaces, as: :owner
  accepts_nested_attributes_for :spaces
  has_many :members
  has_many :organizations, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :load_form_data
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

  def load_form_data
    @new_space = Space.new
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!, except: [:lookup]

  def show
    @user = current_user
  end

  def lookup
    @user = User.find_by_email(params[:email])
    if @user
      render json: {name: @user.name, avatar: @user.avatar.url}
    else
      render json: {}
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    profile_path_url
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def show
    @space = Space.find_by_slug!(params[:space_slug])
  rescue ActiveRecord::RecordNotFound
    record_not_found
  end

  def edit
    @space = Space.find_by_slug!(params[:space_slug])
    render :new
  end

  def new
    redirect_to root_path unless params[:title]
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.owner = current_user
    if @space.save!
      redirect_to "/wiki/#{@space.slug}"
    else
    end
  end

  private

  def record_not_found
    render 'no_space'
  end

  def space_params
    params.require(:space).permit(:name, :slug, :owner, :owner_id)
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  before_action :load_space_resource, only: [:show, :edit]
  before_action :load_page_resource, only: [:show]

  def show
  end

  def edit
    render :new
  end

  def new
    redirect_to root_path unless params[:title]
    @space = Space.find(params[:space_id])
    @article = Page.new
  end

  def create
    @article = Page.new(article_params)
    if @article.save!
      redirect_to "/wiki/#{@article.space.slug}/#{@article.slug}"
    else
      # Add error response
    end
  end

  private

  def load_space_resource
    @space = Space.find_by_slug!(params[:space_slug])
  rescue ActiveRecord::RecordNotFound
    record_not_found(:space)
  end

  def load_page_resource
    @page = Page.find_by_slug!(params[:article_slug])
  rescue ActiveRecord::RecordNotFound
    record_not_found(:page)
  end

  def article_params
    params.require(:page).permit(:name, :slug, :space_id)
  end

  def record_not_found(resource)
    case resource
    when :space
      render 'spaces/no_space'
    when :page
      render 'wiki/no_page'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki Underground</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %>-controller <%= action_name %>-action" style="background: white;">
    <nav style="border-top: 2px solid #2F8A21;" class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to root_url, class: 'navbar-brand' do %>
        <%= image_tag 'wiki_hive.png', width: 200 %>
      <% end %>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <!-- <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <div class="dropdown">
              <%#= link_to '#', class: 'nav-link dropdown', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} do %>
                Spaces <span class="sr-only">(current)</span>
              <%# end %>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
                <%#= link_to 'General', profile_path_url, class: 'dropdown-item' %>
              </div>
            </div>
          </li>

          <li class="nav-item active">
            <%#= link_to '/', class: 'nav-link' do %>
              People
            <%# end %>
          </li>

          <li class="nav-item active">
            <%#= link_to '/', class: 'nav-link' do %>
              Create
            <%# end %>
          </li>

          <li class="nav-item active">
            <%#= link_to '/', class: 'nav-link' do %>
              Help
            < end %>
          </li>
        </ul> -->
        <form class="form-inline my-2 my-lg-0" style="margin: 0 auto;">
          <%= text_field_tag :site_search, '', autocomplete: false, class: 'form-control mr-sm-2 typeahead-search', style: 'width: 700px; background-color: #4D431A; color: white;', placeholder: 'How may I help you?' %>
          <div id='hive-loader' class='hive-loader'>
            <div id='a'>
              <%= image_tag 'hex-green.png' %>
            </div>
            <div id='b'>
              <%= image_tag 'hex-green.png' %>
            </div>
            <div id='c'>
              <%= image_tag 'hex-green.png' %>
            </div>
            <div id='d'>
              <%= image_tag 'hex-green.png' %>
            </div>
            <div id='e'>
              <%= image_tag 'hex-yellow.png' %>
            </div>
            <div id='f'>
              <%= image_tag 'hex-green.png' %>
            </div>
            <div id='g'>
              <%= image_tag 'hex-green.png' %>
            </div>
          </div>
        </form>
      </div>
      <div class='nav-item'>
        <div class="dropdown">
          <%= link_to '#', class: 'profile-dropdown', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} do %>
            <%= image_tag current_user.avatar.url, height: 43, style: 'border: 1px solid #F2C718; padding: 2px;' %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= link_to 'My Profile', '/profile', class: 'dropdown-item' %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </div>
      </div>
    </nav>

    <div style="background: white; height: 100vh; padding: 20px;">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <!-- Modals -->
    <div class="modal fade" id="create_space" tabindex="-1" role="dialog" aria-labelledby="Create Space" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Create a new space</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render 'spaces/new_modal' %>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="create_page" tabindex="-1" role="dialog" aria-labelledby="Create Space" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Create a new page</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-primary">Create</button>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki Underground Devise</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %>-controller <%= action_name %>-action">
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to root_url, class: 'navbar-brand' do %>
        <%= image_tag 'wiki_hive.png', width: 200 %>
      <% end %>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <!-- <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <div class="dropdown">
              <%= link_to '#', class: 'nav-link dropdown', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} do %>
                Spaces <span class="sr-only">(current)</span>
              <% end %>

              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
                <%= link_to 'General', profile_path_url, class: 'dropdown-item' %>
              </div>
            </div>
          </li>

          <li class="nav-item active">
            <%= link_to '/', class: 'nav-link' do %>
              People
            <% end %>
          </li>

          <li class="nav-item active">
            <%= link_to '/', class: 'nav-link' do %>
              Create
            <% end %>
          </li>

          <li class="nav-item active">
            <%= link_to '/', class: 'nav-link' do %>
              Help
            <% end %>
          </li>
        </ul> -->
        <form class="form-inline my-2 my-lg-0" style="margin: 0 auto;">
          <input class="form-control mr-sm-2" type="text" style="width: 700px;" placeholder="How may I help?">
        </form>
      </div>
      <!-- <div class='nav-item'>
        <div class="dropdown">
          <%#= link_to '#', class: 'profile-dropdown', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} do %>
            <%#= image_tag current_user.avatar.url, width: 37, style: 'border: 1px solid #F2C718; padding: 2px;' %>
          <%# end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%#= link_to 'My Profile', profile_path_url, class: 'dropdown-item' %>
            <%#= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </div>
      </div> -->
    </nav>

    <div style="background: white; height: 100vh; padding: 20px;">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/spaces/_new.html.erb
<%= form_for @new_space do |f| %>
  Name: <%= f.text_field :name, id: 'space_name' %><br />
  <%= f.hidden_field :slug, id: 'space_slug' %>
  <%= f.submit %>
<% end %>

app/views/spaces/_new_modal.html.erb
<%= form_for @new_space do |f| %>
  Name: <%= f.text_field :name, id: 'space_name' %><br />
  <%= f.hidden_field :slug, id: 'space_slug' %>
  <%= f.submit %>
<% end %>

app/views/spaces/new.html.erb
<div>
  <%= form_for @space do |f| %>
    <strong>Space Title:</strong><br />
    <div>
      <div style="float: left;">
        <h2><%= params[:title].gsub('_', ' ') %></h2>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :slug, value: params[:title].gsub(' ', '_') %>
      </div>

      <div style="float: right;">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
      <div style="clear: both;"></div>
    </div>
    <hr />
    <strong>Description:</strong>
    <%= text_area_tag :description, nil, id: 'editor' %>
  <% end %>
</div>

app/views/spaces/no_space.html.erb
<h1>
  Whoops! No spaces called <strong><%= params[:space_slug] %></strong> found.
</h1>
<hr />
<div style="padding: 10px; background: #F8F9FA; border: 1px solid #cccccc;">
  <strong>Wiki Hive does not have a space created with this exact name.</strong> Please <%= link_to "search for <i>#{params[:space_slug]}</i> in Wiki Hive".html_safe, '#' %><br />
  <ul>
    <% if user_signed_in? %>
      <li><%= link_to "Start the <strong><i>#{params[:space_slug]}</i></strong> space".html_safe, new_space_path({title: params[:space_slug].gsub(' ', '_')}) %></li>
    <% else %>
      <li><%= link_to 'Log in or create an account', new_user_session_path %> to create the <strong><i><%= params[:space_slug] %></i></strong> space.</li>
    <% end %>
    <li><%= link_to "Search for \"#{params[:space_slug]}\"", '#' %> in existing spaces.</li>
    <li><%= link_to 'Look for spaces within Wiki Hive that link to this title', '#' %></li>
  </ul>
</div>

app/views/spaces/show.html.erb
<h1>
  <%= @space.name %> Space
</h1>
<hr />
<div class='row'>
  <div class='col-lg-12'>
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Articles</h4>
        <h6 class="card-subtitle mb-2 text-muted"><%= @space.pages.count %> Pages</h6>
        <p class="card-text"></p>
        <%= link_to 'Create New Article', new_space_wiki_path(@space), class: 'card-link' %>
        <!-- <a href="#" class="card-link">Another link</a> -->
      </div>
    </div>
  </div>
</div>

app/views/wiki/new.html.erb
<div>
  <%= form_for space_wiki_index_path(@space, @article) do |f| %>
    <strong>Space Title:</strong><br />
    <div>
      <div style="float: left;">
        <h2><%= params[:title].gsub('_', ' ') %></h2>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :slug, value: params[:title].gsub(' ', '_') %>
      </div>

      <div style="float: right;">
        <%= f.submit "Create Article", class: 'btn btn-primary' %>
      </div>
      <div style="clear: both;"></div>
    </div>
    <hr />
    <strong>Content:</strong>
    <%= text_area_tag :content, nil, id: 'editor' %>
  <% end %>
</div>

app/views/wiki/no_page.html.erb
<h1>
  <%= params[:page_slug] %>
</h1>
<hr />
<div style="padding: 10px; background: #F8F9FA; border: 1px solid #cccccc;">
  <strong>Wiki Hive does not have an article with this exact name.</strong> Please <%= link_to "search for <i>#{params[:page_slug]}</i> in Wiki Hive".html_safe, '#' %><br />
  <ul>
    <li><%= link_to 'Log in or create an account', new_user_session_path %> to start the <strong><i><%= params[:page_slug] %></i></strong> article.</li>
    <li><%= link_to "Search for \"#{params[:page_slug]}\"", '#' %> in existing articles.</li>
    <li><%= link_to 'Look for pages within Wiki Hive that link to this title', '#' %></li>
  </ul>
</div>

app/views/wiki/show.html.erb
Wiki Show